# Generated by Django 5.0.4 on 2024-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_machinelearningpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackEndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Back End Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='C/C++ Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalyticsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Data Analytics Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSciencePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Data Science Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontEndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Front End Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullStackPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Full Stack Course', max_length=50)),
                ('transaction_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
